# Generated by Django 4.0.5 on 2022-07-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_alter_pourlogs_flavours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pourlogs',
            name='dispensed_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pourlogs',
            name='drink_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
