# Generated by Django 4.0.5 on 2022-07-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_alter_pourlogs_dispensed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pourlogs',
            name='carbonation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
